### ISSUE TITLE
REQUEST: Support additional command arguments

### ISSUE THREAD

**Issue by sreknob** [compscidr/lolminer-docker#11]
Thanks for putting this together!

I was wondering if you'd be able to add support for additional command arguments like:
```
--algo (in addition to or **in place of** --coin)
--dualalgo
--dualpool
--dualuser
--cclk
--lhrtune
--config (which could solve all of the possible use cases)
```
Either through a conditional entrypoint or variables?

Tried with them as post arguments but not having any love.

Cheers!

EDIT: AND/OR while I'm thinking about it, it might be nice to just be able to pass a config file instead to cover the myriad of use cases and possible future args!

**Comment by compscidr** [comment]
Sure, that should be pretty easy - I'll see if I get a chance this weekend.

**Comment by compscidr** [comment]
okay should be good to go as of: https://github.com/compscidr/lolminer-docker/releases/tag/1.47-c11.4.2

I updated it so you can use any argument that lolminer supports. You can see whats possible with something like:
```docker run --gpus all compscidr/lolminer-docker:nvidia-1.47-c11.4.2 --help``` for nvidia or
```docker run --device=/dev/dri:/dev/dri compscidr/lolminer-docker:amd-1.47-c11.4.2 --help``` for amd

**Comment by sreknob** [comment]
Amazing, thank you! I'll give it a go!
