### ISSUE TITLE
LolMiner Update

### ISSUE THREAD

**Issue by maxwdjoh** [compscidr/lolminer-docker#23]
Hello, I wanted to see if it would be possible to update to the latest version of lolminer. The current image does not support 1.81.

**Comment by compscidr** [comment]
Sorry just saw this now, will update asap.

**Comment by maxwdjoh** [comment]
I was unable to pull the new image. I have listed the logs below. 

2024-01-10T19:29:23Z error pulling image: Error response from daemon: manifest for compscidr/lolminer-docker:ubuntu22.04-cuda-12.2.0-1.82 not found: manifest unknown: manifest unknown
2024-01-10T19:29:23Z error creating container: Error response from daemon: No such image: compscidr/lolminer-docker:ubuntu22.04-cuda-12.2.0-1.82

**Comment by compscidr** [comment]
Yeah, needed to merge the PR first. Once this action completes it should be available: https://github.com/compscidr/lolminer-docker/actions/runs/7480585516

**Comment by compscidr** [comment]
hm actually I need to update the deploy file as well - going to take one more PR. Its been a while and I forgot how this stuff works lol

**Comment by compscidr** [comment]
okay should be when this one finishes: https://github.com/compscidr/lolminer-docker/actions/runs/7480646953

**Comment by maxwdjoh** [comment]
Defiantly understand. I have had to start doing what no IT person does... Take notes on things lol

**Comment by compscidr** [comment]
Okay looked at dockerhub, looks like the latest images are up there now. Going to close, feel free to re-open if there are any issues.

**Comment by maxwdjoh** [comment]
Wanted to see if we could get this updated again?

Thanks

**Comment by compscidr** [comment]
okay should be updated to 1.82a now

**Comment by maxwdjoh** [comment]
Thank you
